[package]
name = "dualsense-rainbow"
version = "0.1.0"
edition = "2024"

[dependencies]
hidapi = { version = "2.6.3", features = ["static"] }
winapi = { version = "0.3", features = ["consoleapi", "wincon"] }
